### ISSUE TITLE
Error with tensorflow in R

### ISSUE THREAD

**Issue by ghost** [quon-titative-biology/examples#2]
Hi,
I'm new to machine learning and had a bit difficult time getting scAlign function work.
I have installed tensorflow 2.0.0 (with or without gpu, I do have gpu in my computer) and in R. Both of them seems to work when test in either environment. However if I ran this:

`scAlignCB = scAlign(scAlignCB, options=scAlignOptions(steps=5000, log.every=5000, norm=TRUE,  batch.norm.layer=TRUE, early.stop=FALSE, architecture="small"), encoder.data="scale.data",  decoder.data="logcounts",  supervised='none', run.encoder=TRUE,run.decoder=TRUE, log.dir=file.path(results.dir, 'models','gene_input'),  device="CPU")`
I got error:

> Error in value[[3L]](cond) : 
  Error with system install of tensorflow, check R for Tensorflow docs.

I'm not sure if this is a version compatibility issue or something else. Could anyone kindly help? 

I followed this installing tensorflow in windows using pip:https://www.tensorflow.org/install/pip
and this is how I installed in R:
`library(tensorflow)`
`install_tensorflow() `

Thank you very much in advance!

**Comment by UCDNJJ** [comment]
Hi,

You are right, the error is due to a version compatibility issue. scAlign currently requires Tensorflow 1, preferably version 1.15 (which is both cpu/gpu enabled). We plan to update scAlign to Tensorflow 2 in the next few months.

**Comment by ghost** [comment]
Fixed, version 1.15 (both in R and in system) works fine. Thanks a lot!

**Comment by UCDNJJ** [comment]
Awesome! Let us know if you have any questions or run into any further issues.
